export default [
  {
    id: 0,
    title: "The Road Ahead",
    author: "Bill Gates",
    date: "2023-04-11",
    sell: 1065,
    status: "true",
  },
  {
    id: 1,
    title: "Walter Isaacson",
    author: "Steve Jobs",
    date: "2021-07-13",
    sell: 66,
    status: "true",
  },
  {
    id: 2,
    title: "Mockingjay: The Final Book of The Hunger Games",
    author: "Suzanne Collins",
    date: "2023-04-11",
    sell: 91,
    status: "true",
  },
  {
    id: 3,
    title: "communication screte",
    author: "Brothers",
    date: "2023-04-11",
    sell: 86,
    status: "true",
  },
  {
    id: 4,
    title: "stoke market",
    author: "Arvind arora",
    date: "2021-07-13",
    sell: 34,
    status: "true",
  },
  {
    id: 5,
    title: "Business Communication",
    author: "Omprakash Biyani ",
    date: "2023-04-13",
    sell: 90,
    status: "true",
  },
  {
    id: 6,
    title: "Psychology 2e",
    author: "Marilyn D. Lovett ",
    date: "2023-04-13",
    sell: 49,
    status: "true",
  },
  {
    id: 7,
    title: "General Psychology",
    author: "S K Mangal",
    date: "2023-04-13",
    sell: 89,
    status: "true",
  },
  {
    id: 8,
    title: "The Little Book ",
    author: "Emily Ralls",
    date: "2023-04-13",
    sell: 81,
    status: "true",
  },
  {
    id: 9,
    title: "Learning Statistics with R",
    author: "Daniel Navarro",
    date: "2023-04-13",
    sell: 102,
    status: "true",
  },
];
