export default [
    {
      id: 0,
      title: "The Road Ahead",
      author: "Bill Gates",
      Date: "2023-04-11",
      Sell: 1065,
      Status: "true",
    },
    {
      id: 1,
      title: "Walter Isaacson",
      author: "Steve Jobs",
      Date: "2021-07-13",
      Sell: 66,
      Status: "true",
    },
    {
      id: 2,
      title: "Mockingjay: The Final Book of The Hunger Games",
      author: "Suzanne Collins",
      Date: "2023-04-11",
      Sell: 91,
      Status: "true",
    },
    {
      id: 3,
      title: "communication screte",
      author: "Brothers",
      Date: "2023-04-11",
      Sell: 86,
      Status: "true",
    },
    {
      id: 4,
      title: "stoke market",
      author: "Arvind arora",
      Date: "2021-07-13",
      Sell: 34,
      Status: "true",
    },
    {
      id: 5,
      title: "Business Communication",
      author: "Omprakash Biyani ",
      Date: "2023-04-13",
      Sell: 90,
      Status: "true",
    },
    {
      id: 6,
      title: "Psychology 2e",
      author: "Marilyn D. Lovett ",
      Date: "2023-04-13",
      Sell: 49,
      Status: "true",
    },
    {
      id: 7,
      title: "General Psychology",
      author: "S K Mangal",
      Date: "2023-04-13",
      Sell: 89,
      Status: "true",
    },
    {
      id: 8,
      title: "The Little Book ",
      author: "Emily Ralls",
      Date: "2023-04-13",
      Sell: 81,
      Status: "true",
    },
    {
      id: 9,
      title: "Learning Statistics with R",
      author: "Daniel Navarro",
      Date: "2023-04-13",
      Sell: 102,
      Status: "true",
    },
  ];